apiVersion: apps/v1
kind: Deployment
metadata:
    name: signabio.deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app:  signabio_app2
    template:
        metadata:
            labels:
                app: signabio_app2
        spec:
            containers:
              - name: app1 
                image: docker.io/sreekesh52/signabio_app2:v2
                imagePullPolicy: IfNotPresent
                ports:
                   - containerPort: 9091

---
    apiVersion: v1
    kind: Service
    metadata:
        name: signabio-service
    spec:
        selector:
            app: signabio_app2
        type: NodePort
        ports:
            - protocol: TCP
              port: 9091
              targetPort: 9091
              nodePort: 31101
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: signabio.ingress
      namespace: default
    spec:
      rules:
        - host: signabioapp.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: signabio-service
                  port:
                    number: 9091